export const SYMBOLS = {
  ALL: { description: "Albania Lek", symbol: "Lek" },
  AFN: { description: "Afghanistan Afghani", symbol: "؋" },
  ARS: { description: "Argentina Peso", symbol: "$" },
  AWG: { description: "Aruba Guilder", symbol: "ƒ" },
  AUD: { description: "Australia Dollar", symbol: "$" },
  AZN: { description: "Azerbaijan Manat", symbol: "₼" },
  BSD: { description: "Bahamas Dollar", symbol: "$" },
  BBD: { description: "Barbados Dollar", symbol: "$" },
  BYN: { description: "Belarus Ruble", symbol: "Br" },
  BZD: { description: "Belize Dollar", symbol: "BZ$" },
  BMD: { description: "Bermuda Dollar", symbol: "$" },
  BOB: { description: "Bolivia Bolíviano", symbol: "$b" },
  BAM: { description: "Bosnia and Herzegovina Convertible Mark", symbol: "KM" },
  BWP: { description: "Botswana Pula", symbol: "P" },
  BGN: { description: "Bulgaria Lev", symbol: "лв" },
  BRL: { description: "Brazil Real", symbol: "R$" },
  BND: { description: "Brunei Darussalam Dollar", symbol: "$" },
  KHR: { description: "Cambodia Riel", symbol: "៛" },
  CAD: { description: "Canada Dollar", symbol: "$" },
  KYD: { description: "Cayman Islands Dollar", symbol: "$" },
  CLP: { description: "Chile Peso", symbol: "$" },
  CNY: { description: "China Yuan Renminbi", symbol: "¥" },
  COP: { description: "Colombia Peso", symbol: "$" },
  CRC: { description: "Costa Rica Colon", symbol: "₡" },
  HRK: { description: "Croatia Kuna", symbol: "kn" },
  CUP: { description: "Cuba Peso", symbol: "₱" },
  CZK: { description: "Czech Republic Koruna", symbol: "Kč" },
  DKK: { description: "Denmark Krone", symbol: "kr" },
  DOP: { description: "Dominican Republic Peso", symbol: "RD$" },
  XCD: { description: "East Caribbean Dollar", symbol: "$" },
  EGP: { description: "Egypt Pound", symbol: "£" },
  SVC: { description: "El Salvador Colon", symbol: "$" },
  EUR: { description: "Euro Member Countries", symbol: "€" },
  FKP: { description: "Falkland Islands (Malvinas) Pound", symbol: "£" },
  FJD: { description: "Fiji Dollar", symbol: "$" },
  GHS: { description: "Ghana Cedi", symbol: "¢" },
  GIP: { description: "Gibraltar Pound", symbol: "£" },
  GTQ: { description: "Guatemala Quetzal", symbol: "Q" },
  GGP: { description: "Guernsey Pound", symbol: "£" },
  GYD: { description: "Guyana Dollar", symbol: "$" },
  HNL: { description: "Honduras Lempira", symbol: "L" },
  HKD: { description: "Hong Kong Dollar", symbol: "$" },
  HUF: { description: "Hungary Forint", symbol: "Ft" },
  ISK: { description: "Iceland Krona", symbol: "kr" },
  INR: { description: "India Rupee", symbol: "" },
  IDR: { description: "Indonesia Rupiah", symbol: "Rp" },
  IRR: { description: "Iran Rial", symbol: "﷼" },
  IMP: { description: "Isle of Man Pound", symbol: "£" },
  ILS: { description: "Israel Shekel", symbol: "₪" },
  JMD: { description: "Jamaica Dollar", symbol: "J$" },
  JPY: { description: "Japan Yen", symbol: "¥" },
  JEP: { description: "Jersey Pound", symbol: "£" },
  KZT: { description: "Kazakhstan Tenge", symbol: "лв" },
  KPW: { description: "Korea (North) Won", symbol: "₩" },
  KRW: { description: "Korea (South) Won", symbol: "₩" },
  KGS: { description: "Kyrgyzstan Som", symbol: "лв" },
  LAK: { description: "Laos Kip", symbol: "₭" },
  LBP: { description: "Lebanon Pound", symbol: "£" },
  LRD: { description: "Liberia Dollar", symbol: "$" },
  MKD: { description: "Macedonia Denar", symbol: "ден" },
  MYR: { description: "Malaysia Ringgit", symbol: "RM" },
  MUR: { description: "Mauritius Rupee", symbol: "₨" },
  MXN: { description: "Mexico Peso", symbol: "$" },
  MNT: { description: "Mongolia Tughrik", symbol: "₮" },
  MZN: { description: "Mozambique Metical", symbol: "MT" },
  NAD: { description: "Namibia Dollar", symbol: "$" },
  NPR: { description: "Nepal Rupee", symbol: "₨" },
  ANG: { description: "Netherlands Antilles Guilder", symbol: "ƒ" },
  NZD: { description: "New Zealand Dollar", symbol: "$" },
  NIO: { description: "Nicaragua Cordoba", symbol: "C$" },
  NGN: { description: "Nigeria Naira", symbol: "₦" },
  NOK: { description: "Norway Krone", symbol: "kr" },
  OMR: { description: "Oman Rial", symbol: "﷼" },
  PKR: { description: "Pakistan Rupee", symbol: "₨" },
  PAB: { description: "Panama Balboa", symbol: "B/." },
  PYG: { description: "Paraguay Guarani", symbol: "Gs" },
  PEN: { description: "Peru Sol", symbol: "S/." },
  PHP: { description: "Philippines Peso", symbol: "₱" },
  PLN: { description: "Poland Zloty", symbol: "zł" },
  QAR: { description: "Qatar Riyal", symbol: "﷼" },
  RON: { description: "Romania Leu", symbol: "lei" },
  RUB: { description: "Russia Ruble", symbol: "₽" },
  SHP: { description: "Saint Helena Pound", symbol: "£" },
  SAR: { description: "Saudi Arabia Riyal", symbol: "﷼" },
  RSD: { description: "Serbia Dinar", symbol: "Дин." },
  SCR: { description: "Seychelles Rupee", symbol: "₨" },
  SGD: { description: "Singapore Dollar", symbol: "$" },
  SBD: { description: "Solomon Islands Dollar", symbol: "$" },
  SOS: { description: "Somalia Shilling", symbol: "S" },
  ZAR: { description: "South Africa Rand", symbol: "R" },
  LKR: { description: "Sri Lanka Rupee", symbol: "₨" },
  SEK: { description: "Sweden Krona", symbol: "kr" },
  CHF: { description: "Switzerland Franc", symbol: "CHF" },
  SRD: { description: "Suriname Dollar", symbol: "$" },
  SYP: { description: "Syria Pound", symbol: "£" },
  TWD: { description: "Taiwan New Dollar", symbol: "NT$" },
  THB: { description: "Thailand Baht", symbol: "฿" },
  TTD: { description: "Trinidad and Tobago Dollar", symbol: "TT$" },
  TRY: { description: "Turkey Lira", symbol: "" },
  TVD: { description: "Tuvalu Dollar", symbol: "$" },
  UAH: { description: "Ukraine Hryvnia", symbol: "₴" },
  GBP: { description: "United Kingdom Pound", symbol: "£" },
  USD: { description: "United States Dollar", symbol: "$" },
  UYU: { description: "Uruguay Peso", symbol: "$U" },
  UZS: { description: "Uzbekistan Som", symbol: "лв" },
  VEF: { description: "Venezuela Bolívar", symbol: "Bs" },
  VND: { description: "Viet Nam Dong", symbol: "₫" },
  YER: { description: "Yemen Rial", symbol: "﷼" },
  ZWD: { description: "Zimbabwe Dollar", symbol: "Z$" },

  AED: { description: "United Arab Emirates Dirham", code: "AED" },
  AMD: { description: "Armenian Dram", code: "AMD" },
  AOA: { description: "Angolan Kwanza", code: "AOA" },
  BDT: { description: "Bangladeshi Taka", code: "BDT" },
  BHD: { description: "Bahraini Dinar", code: "BHD" },
  BIF: { description: "Burundian Franc", code: "BIF" },
  BTC: { description: "Bitcoin", code: "BTC" },
  BTN: { description: "Bhutanese Ngultrum", code: "BTN" },
  CDF: { description: "Congolese Franc", code: "CDF" },
  CLF: { description: "Chilean Unit of Account (UF)", code: "CLF" },
  CNH: { description: "Chinese Yuan (Offshore)", code: "CNH" },
  CUC: { description: "Cuban Convertible Peso", code: "CUC" },
  CVE: { description: "Cape Verdean Escudo", code: "CVE" },
  DJF: { description: "Djiboutian Franc", code: "DJF" },
  DZD: { description: "Algerian Dinar", code: "DZD" },
  ERN: { description: "Eritrean Nakfa", code: "ERN" },
  ETB: { description: "Ethiopian Birr", code: "ETB" },
  GEL: { description: "Georgian Lari", code: "GEL" },
  GMD: { description: "Gambian Dalasi", code: "GMD" },
  GNF: { description: "Guinean Franc", code: "GNF" },
  HTG: { description: "Haitian Gourde", code: "HTG" },
  IQD: { description: "Iraqi Dinar", code: "IQD" },
  JOD: { description: "Jordanian Dinar", code: "JOD" },
  KES: { description: "Kenyan Shilling", code: "KES" },
  
  KMF: { description: "Comorian Franc", code: "KMF" },
  KWD: { description: "Kuwaiti Dinar", code: "KWD" },
  LSL: { description: "Lesotho Loti", code: "LSL" },
  LYD: { description: "Libyan Dinar", code: "LYD" },
  MAD: { description: "Moroccan Dirham", code: "MAD" },
  MDL: { description: "Moldovan Leu", code: "MDL" },
  MGA: { description: "Malagasy Ariary", code: "MGA" },
  
  MMK: { description: "Myanma Kyat", code: "MMK" },
  MOP: { description: "Macanese Pataca", code: "MOP" },
  MRO: { description: "Mauritanian Ouguiya (pre-2018)", code: "MRO" },
  MRU: { description: "Mauritanian Ouguiya", code: "MRU" },
  MVR: { description: "Maldivian Rufiyaa", code: "MVR" },
  MWK: { description: "Malawian Kwacha", code: "MWK" },
  PGK: { description: "Papua New Guinean Kina", code: "PGK" },
  RWF: { description: "Rwandan Franc", code: "RWF" },
  SDG: { description: "Sudanese Pound", code: "SDG" },
  SLL: { description: "Sierra Leonean Leone", code: "SLL" },
  SSP: { description: "South Sudanese Pound", code: "SSP" },
  STD: { description: "São Tomé and Príncipe Dobra (pre-2018)", code: "STD" },
  STN: { description: "São Tomé and Príncipe Dobra", code: "STN" },
  SZL: { description: "Swazi Lilangeni", code: "SZL" },
  TJS: { description: "Tajikistani Somoni", code: "TJS" },
  TMT: { description: "Turkmenistani Manat", code: "TMT" },
  TND: { description: "Tunisian Dinar", code: "TND" },
  TOP: { description: "Tongan Pa'anga", code: "TOP" },
  VUV: { description: "Vanuatu Vatu", code: "VUV" },
  WST: { description: "Samoan Tala", code: "WST" },
  XAF: { description: "CFA Franc BEAC", code: "XAF" },
  XAG: { description: "Silver Ounce", code: "XAG" },
  XAU: { description: "Gold Ounce", code: "XAU" },
  XDR: { description: "Special Drawing Rights", code: "XDR" },
  XOF: { description: "CFA Franc BCEAO", code: "XOF" },
  XPD: { description: "Palladium Ounce", code: "XPD" },
  XPF: { description: "CFP Franc", code: "XPF" },
  XPT: { description: "Platinum Ounce", code: "XPT" },
  ZMW: { description: "Zambian Kwacha", code: "ZMW" },
  ZWL: { description: "Zimbabwean Dollar", code: "ZWL" },
  
};
